import {TraitData} from '../data/traits'

// Mock trait data covering all required categories for testing
export const mockTraitData: TraitData[] = [
  // Location - District
  {
    id: 1,
    name: 'Mountains',
    stage: 'Final',
    category1: 'Location',
    category2: 'District',
    searchableTags: ['Location'],
    devTags: [],
    frontIndex: 2000,
  },
  // Location - Time
  {
    id: 2,
    name: 'Night',
    stage: 'Final',
    category1: 'Location',
    category2: 'Time',
    searchableTags: ['Time'],
    devTags: [],
    frontIndex: 3000,
  },
  // Body - Eyes - Style
  {
    id: 3,
    name: 'Outline',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Style',
    searchableTags: ['Eye Style'],
    devTags: [],
    frontIndex: 5000,
  },
  // Body - Eyes - Colour
  {
    id: 4,
    name: 'Blue Eyes',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Colour',
    searchableTags: ['Eye Colour'],
    devTags: [],
    frontIndex: 15000,
  },
  {
    id: 5,
    name: 'Brown Eyes',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Colour',
    searchableTags: ['Eye Colour'],
    devTags: [],
    frontIndex: 15000,
  },
  // Body - Eyes - Lashes
  {
    id: 6,
    name: 'Basic Lashes',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Lashes',
    searchableTags: ['Eye Lashes'],
    devTags: [],
    frontIndex: 6000,
  },
  // Body - Skin - Tone
  {
    id: 7,
    name: 'Almond',
    stage: 'Final',
    category1: 'Body',
    category2: 'Skin',
    category3: 'Tone',
    searchableTags: ['Skin Tone'],
    devTags: [],
    frontIndex: 4000,
  },
  // Body - Hair - Style
  {
    id: 8,
    name: 'Twin Braids',
    stage: 'Final',
    category1: 'Body',
    category2: 'Hair',
    category3: 'Style',
    searchableTags: ['Hair Style'],
    devTags: [],
    frontIndex: 7000,
  },
  // Body - Hair - Colour
  {
    id: 9,
    name: 'Blonde',
    stage: 'Final',
    category1: 'Body',
    category2: 'Hair',
    category3: 'Colour',
    searchableTags: ['Hair Colour'],
    devTags: [],
    frontIndex: 8000,
  },
  // Body - Expression
  {
    id: 10,
    name: 'Smile',
    stage: 'Final',
    category1: 'Body',
    category2: 'Expression',
    searchableTags: ['Expression'],
    devTags: [],
    frontIndex: 9000,
  },
  // Pose
  {
    id: 11,
    name: 'Basic Pose',
    stage: 'Final',
    category1: 'Pose',
    category2: 'Stick Figure Poses',
    searchableTags: ['Pose'],
    devTags: [],
    frontIndex: 1000,
  },
  // Additional traits for testing
  {
    id: 12,
    name: 'Green Eyes',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Colour',
    searchableTags: ['Eye Colour'],
    devTags: [],
    frontIndex: 15000,
  },
  {
    id: 13,
    name: 'Test Accessory',
    stage: 'Final',
    category1: 'Accessory',
    category2: 'Animal',
    searchableTags: ['Accessory'],
    devTags: [],
    frontIndex: 2000,
  },
  // Additional traits for the working test
  {
    id: 14,
    name: 'Bats',
    stage: 'Final',
    category1: 'Accessory',
    category2: 'Animal',
    searchableTags: ['Halloween', 'Animal'],
    devTags: [],
    frontIndex: 1000,
  },
  {
    id: 15,
    name: 'Dark Blue Tie',
    stage: 'Final',
    category1: 'Accessory',
    category2: 'Bows/Ties',
    searchableTags: [],
    devTags: [],
    frontIndex: 6000,
  },
  {
    id: 16,
    name: 'Black Eyes',
    stage: 'Final',
    category1: 'Body',
    category2: 'Eyes',
    category3: 'Colour',
    searchableTags: ['Eye Colour'],
    devTags: [],
    frontIndex: 15000,
  },
  {
    id: 17,
    name: 'Red Shirt',
    stage: 'Final',
    category1: 'Clothing',
    category2: 'Tops',
    searchableTags: ['Shirt'],
    devTags: [],
    frontIndex: 5000,
  },
]
